#!/bin/bash
. $(dirname $0)/msvcenv.sh

export INCLUDE="$MSVCDIR_UNIX/include;$SDKINCLUDE_UNIX/shared;$SDKINCLUDE_UNIX/ucrt;$SDKINCLUDE_UNIX/um;$SDKINCLUDE_UNIX/winrt"
export LIB="$MSVCDIR_UNIX/lib/$ARCH;$SDKLIB_UNIX/ucrt/$ARCH;$SDKLIB_UNIX/um/$ARCH"
export LIBPATH="$LIB"

exec -a lld-link rust-lld "$@"