#!/usr/bin/env bash

SDK=kits/10
BASE=/opt/msvc
MSVCVER=14.13.26128
SDKVER=10.0.16299.0
ARCH=x86
MSVCDIR="$BASE/vc/tools/msvc/$MSVCVER"
SDKINCLUDE="$BASE/$SDK/include/$SDKVER"
SDKLIB="$BASE/$SDK/lib/$SDKVER"

export INCLUDE="$MSVCDIR/include;$SDKINCLUDE/shared;$SDKINCLUDE/ucrt;$SDKINCLUDE/um;$SDKINCLUDE/winrt"
export LIB="$MSVCDIR/lib/$ARCH;$SDKLIB/ucrt/$ARCH;$SDKLIB/um/$ARCH"
export LIBPATH="$LIB"
